name: CI

on:
  push:
    branches:
      - main

jobs:
  build_dev_job:
    runs-on: self-hosted
    strategy:
      matrix:
        NUGET_VERSION: ['4.4.1']
    steps:
      - name: Install NuGet CLI
        run: choco install nuget.commandline --version=$NUGET_VERSION -y
##Test
      - name: Build project
        run: |
          nuget help
          nuget restore
          msbuild ./ /p:DeployOnBuild=true /p:PublishProfile=FolderProfile.pubxml
